version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    networks:
      - wp-network

  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - wp-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

  ngrok:
    image: wernight/ngrok
    environment:
      NGROK_AUTHTOKEN: your-ngrok-token
      NGROK_REGION: eu
      NGROK_HOSTNAME: your-custom-subdomain.ngrok.io
    command: ngrok http nginx:80
    depends_on:
      - nginx
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
    driver: bridge
